name: ModionePlugin3.0
version: '${project.version}'
main: me.modione.modioneplugin.ModionePlugin
api-version: 1.18

commands:
  gms:
    description: Sets your Gamemode to Survival-Mode!
    permission: modione.gamemodes
  gmc:
    description: Sets your Gamemode to Creative-Mode!
    permission: modione.gamemodes
  gmsp:
    description: Sets your Gamemode to Spectator-Mode!
    permission: modione.gamemodes
  gma:
    description: Sets your Gamemode to Adventure-Mode!
    permission: modione.gamemodes
  enderchest:
    description: opens your Ender chest
    aliases:
      - ec
    permission: op
  where:
    description: Shows where you are
  day:
    description: Sets the time to day
    aliases:
      - daytime
      - dt
    permission: op
  admin:
    description: Opens the Admin Panel!
    aliases:
      - adminpanel
      - ap

permissions:
  modione.gamemodes:
    description: Allows you to change your gamemode.
    default: op
